### ISSUE TITLE
How are transactions supported?

### ISSUE THREAD

**Issue by brandonros** [Koka/odbc-rs#76]
An example would be a huge help!

**Comment by Koka** [comment]
Hi @brandonros, 

I'm afraid there is no ergonomic way for transaction management was built into this crate, but it's still possible using low-level ODBC interface directly through [odbc-sys](https://github.com/pacman82/odbc-sys) crate (using `SQLSetConnectAttr` and `SQLEndTran` functions as described in [MSDN](https://msdn.microsoft.com/en-us/library/ms131281(v=sql.120).aspx)).

I hope some time later we could create more ergonomic way to handle transactions.

May be a bit later I'll have some spare time to at least create an example of low-level transaction management.

Thanks for your interest

**Comment by brandonros** [comment]
Does this mean there is no Rust code out there that supports ODBC transactions?

**Comment by Koka** [comment]
@brandonros Not yet. However I've posted a PR with transaction support to underlying crate, so you could either wait it to be merged or use it as a reference to guide your own implementation.

**Comment by brandonros** [comment]
Link to PR?

**Comment by Koka** [comment]
https://github.com/pacman82/odbc-safe/pull/6

**Comment by bbigras** [comment]
Any progress on this?

**Comment by Koka** [comment]
@bbigras Unfortunately I have no free time at all, so not much

**Comment by brandonros** [comment]
What needs to be done?

Does it sound accurate that ODBC performance using this + IBM DB2 drivers would be much worse than Java’s JDBC offering?

Regards,

Brandon

________________________________

**Comment by Koka** [comment]
What is needed is to finish migration of this crate to use underlying odbc-safe crate everywhere instead of outdated custom implementation from this crate. I’ve started some work on this in v2 branch, but it’s far from completion.

You can try to use of odbc-safe crate directly, but it’s not ergonomic at all.

Answering your question about performance - this crate don’t introduce additional performance penalty, so it’s the question to ODBC and JDBC driver authors. If you want a production quality solution I’d recommend to stick to JDBC

**Comment by Koka** [comment]
Released transaction support as 0.15.0
